# -*- coding: utf-8 -*-
import codecs

# Full Translation Map (English -> Ukrainian)
# Based on previous efforts.
# Includes ALL strings found in EN_GAME.LTXT
translation_map = {
    "Damage": "Пошкодження",
    "Felony": "Злочин",
    "Proximity": "Близькість",
    "Best": "Найкращий",
    "Cone": "Конус",
    "Gate": "Ворота",
    "Check": "Чек",
    "Cones": "Конуси",
    "Gates": "Ворота",
    "Checks": "Чеки",
    "-1 second": "-1 секунда",
    "Flags": "Прапори",
    "Lap": "Коло",
    "You got the flag!": "Ви взяли прапор!",
    "Draw!": "Нічия!",
    "Well done!": "Чудово!",
    "You've been caught!": "Вас спіймали!",
    "Out of tape": "Закінчилась плівка",
    "DEMO": "ДЕМО",
    "Fast forward": "Перемотка",
    "Auto direct": "Авто-режисер",
    "Please wait...": "Будь ласка зачекайте...",
    "Please insert DISC 1": "Вставте ДИСК 1",
    "Please insert DISC 2": "Вставте ДИСК 2",
    "No DISC inserted": "ДИСК не вставлено",
    "Incorrect DISC inserted": "Невірний ДИСК",
    "Checking...": "Перевірка...",
    "Are You Sure?": "Ви впевнені?",
    "Paused": "Пауза",
    "Mission Complete": "Місія Виконана",
    "Mission Failed": "Місія Провалена",
    "Game Over": "Гру Закінчено",
    "High Scores": "Рекорди",
    "Enter Name": "Введіть Ім'я",
    "Quit to system?": "Вихід в систему?",
    "Loading configuration...": "Завантаження конфігурації...",
    "Loading error": "Помилка завантаження",
    "No saved data": "Немає збережених даних",
    "Saving configuration...": "Збереження конфігурації...",
    "Saving error": "Помилка збереження",
    "Loading progress...": "Завантаження прогресу...",
    "Saving progress...": "Збереження прогресу...",
    "OK": "ОК",
    "YES": "ТАК",
    "NO": "НІ",
    "Save game": "Зберегти гру",
    "Save replay": "Зберегти повтор",
    "Continue": "Продовжити",
    "Show Map": "Показати Карту",
    "Restart": "Рестарт",
    "Sfx Volume": "Гучність Ефектів",
    "Music Volume": "Гучність Музики",
    "Film Director": "Режисер",
    "Quick Replay": "Швидкий Повтор",
    "Exit": "Вихід",
    "Back": "Назад",
    "Rotation": "Обертання",
    "Move": "Рух",
    "Skip cutscene": "Пропустити",
    "Retry mission": "Спробувати ще",
    "Play again": "Грати знову",
    "View table": "Таблиця",
    "Enter score": "Введіть рахунок",
    "Insert Controller in Port 1": "Вставте контролер в Порт 1",
    "Insert Controller in Port 2": "Вставте контролер в Порт 2",
    "Incorrect controller in Port 1": "Невірний контролер в Порт 1",
    "Incorrect controller in Port 2": "Невірний контролер в Порт 2",
    "Player 1": "Гравець 1",
    "Player 2": "Гравець 2",
    "Name": "Ім'я",
    "Time": "Час",
    "Sorry, no secrets": "Вибачте, немає секретів",
    "Mountain pass": "Гірський перевал",
    "Race track": "Гоночний трек",
    "Invincibility": "Безсмертя",
    "Immunity": "Імунітет",
    "Bonus Gallery": "Бонус Галерея",
    "Mini Cars": "Міні Авто",
    "Pause": "Пауза",
    "Play": "Грати",
    "Auto Director": "Авто Режисер",
    "Fast Forward": "Швидка Перемотка",
    "Frame Advance": "Покадрово",
    "Rewind to beginning": "Перемотка на початок",
    "Add Camera": "Додати Камеру",
    "Edit Camera": "Редагувати Камеру",
    "In Car": "В авто",
    "Chase Camera": "Камера Погоні",
    "Tripod Camera": "Штатив",
    "Move Camera Start": "Рух камери старт",
    "Delete Camera": "Видалити Камеру",
    "Accept": "Прийняти",
    "You or Pursuer": "Ви чи переслідувач",
    "Move Camera": "Рух Камери",
    "Lock to Car": "Слідувати за авто",
    "Rotate": "Обертати",
    "Zoom": "Зум",
    "Getaway is": "Втеча це",
    "Time": "Час",
    "Condition": "Умова",
    "Dusk": "Сутінки",
    "Day": "День",
    "Dawn": "Світанок",
    "Night": "Ніч",
    "Clear": "Ясно",
    "Rainy": "Дощ",
    "Wet": "Волого",
    "Language": "Мова",
    "Undercover": "Під прикриттям",
    "Take A Ride": "Поїздка",
    "Driving Games": "Ігри",
    "Multiplayer": "Мультиплеєр",
    "Options": "Опції",
    "Replays": "Повтори",
    "Secret": "Секрет",
    "Chicago": "Чикаго",
    "Havana": "Гавана",
    "Vegas": "Вегас",
    "Rio": "Ріо",
    "New Game": "Нова Гра",
    "Load Game": "Завантажити гру",
    "Replay Mission": "Переграти місію",
    "View Cutscenes": "Відеоролики",
    "Load Replay": "Завантажити повтор",
    "Show Chase 1": "Показати Погоню 1",
    "Show Chase 2": "Показати Погоню 2",
    "Show Chase 3": "Показати Погоню 3",
    "Show Chase 4": "Показати Погоню 4",
    "Quick Chase": "Швидка Погоня",
    "Quick Getaway": "Швидка Втеча",
    "Gate Racing": "Перегони",
    "Trailblazer": "Першопроходець",
    "Checkpoint": "Чекпоінт",
    "Survival": "Виживання",
    "Cops 'n' Robbers": "Копи та Грабіжники",
    "Capture the Flag": "Захоплення Прапора",
    "Game 1": "Гра 1",
    "Game 2": "Гра 2",
    "Not Available": "Недоступно",
    "Use directional buttons": "Використовуйте стрілки",
    "To Move Screen": "Для переміщення",
    "Sound": "Звук",
    "Gameplay": "Геймплей",
    "Center Screen": "Центрування",
    "Save Settings": "Зберегти Налаштування",
    "Load Settings": "Завантажити Налаштування",
    "Previous": "Попередній",
    "Select": "Вибрати",
    "Next": "Наступний",
    "Choose A Ride": "Виберіть Авто",
    "Cop Difficulty": "Складність Копів",
    "Subtitles": "Субтитри",
    "Vibration": "Вібрація",
    "Controller": "Контролер",
    "Easy": "Легко",
    "Medium": "Середньо",
    "Hard": "Важко",
    "On": "Увімк", # "Увімк" for On
    "Off": "Вимк", # "Вимк" for Off
    "Surveillance tip off": "Наводка стеження",
    "Auto Testing": "Авто Тестування",
    "Lenny gets caught": "Ленні спіймали",
    "Director's Cut": "Режисерська версія",
    "Choose A Cutscene": "Виберіть Ролик",
    "Sfx": "Ефекти",
    "Music": "Музика",
    "Set Volume Levels": "Гучність",
    "Single Player": "Однокористувацька",
    "Mountain Pass": "Гірський Перевал",
    "Race Track": "Гоночний Трек",
    "River North": "Рівер Норт",
    "Cabrini Green": "Кабріні Грін",
    "Plaza de Revolucion": "Площа Революції",
    "Old Havana": "Стара Гавана",
    "Downtown": "Центр",
    "The Lakes": "Озера",
    "Centro": "Центро",
    "Flamengo": "Фламенго"
}

def translate_file(input_path, output_path):
    with open(input_path, 'r', encoding='utf-8') as f_in:
        lines = f_in.readlines()
    
    with codecs.open(output_path, 'w', 'cp1251') as f_out:
        for i, line in enumerate(lines):
            original = line.strip()
            translated = translation_map.get(original)
            
            if not translated:
                # If no translation found, use original or mark it
                print(f"Warning: No translation for line {i+1}: '{original}'")
                translated = original # Fallback
            
            f_out.write(translated + '\r\n')

if __name__ == "__main__":
    translate_file("github_assets/DRIVER2/LANG/EN_GAME.LTXT", "github_assets/DRIVER2/LANG/UA_GAME.LTXT")
    print("UA_GAME.LTXT generated from EN_GAME.LTXT structure.")
