#!/bin/bash
# Mission Translation Editor - Quick Start Guide

echo "🎯 Mission Translation Editor"
echo "=============================="
echo ""
echo "Файли місій знаходяться тут:"
echo "  data/DRIVER2/MISSIONS/UA/*.D2MS"
echo ""
echo "ВАРІАНТ 1: Редагування в Hex Fiend (найпростіше)"
echo "-------------------------------------------------"
echo "1. Встановіть Hex Fiend (безкоштовний): https://hexfiend.com"
echo "2. Відкрийте .D2MS файл"
echo "3. Text Encoding -> Windows Cyrillic (CP1251)"
echo "4. Знайдіть текст і редагуйте напряму"
echo "5. Збережіть"
echo ""
echo "ВАРІАНТ 2: Редагування в VS Code"
echo "---------------------------------"
echo "1. Відкрийте .D2MS файл в VS Code"
echo "2. Натисніть на кодування внизу справа (UTF-8)"
echo "3. Виберіть 'Reopen with Encoding' -> 'Cyrillic (Windows 1251)'"
echo "4. Знайдіть текст (він буде серед бінарних даних)"
echo "5. Редагуйте обережно (не чіпайте бінарні дані!)"
echo "6. Збережіть з тим же кодуванням"
echo ""
echo "ВАРІАНТ 3: Python скрипт (автоматичний)"
echo "---------------------------------------"
echo "Витягнути текст для редагування:"
echo "  python3 tools/localization/d2ms_editor.py --extract \\"
echo "    data/DRIVER2/MISSIONS/UA/M1.D2MS \\"
echo "    M1_edit.txt"
echo ""
echo "Редагуйте M1_edit.txt в будь-якому редакторі (UTF-8)"
echo ""
echo "Вставити назад:"
echo "  python3 tools/localization/d2ms_editor.py --inject \\"
echo "    M1_edit.txt \\"
echo "    data/DRIVER2/MISSIONS/UA/M1.D2MS"
echo ""
echo "Список всіх місій:"
echo "  python3 tools/localization/d2ms_editor.py --list \\"
echo "    data/DRIVER2/MISSIONS/UA"
echo ""
echo "⚠️  УВАГА: Завжди робіть бекап перед редагуванням!"
echo "  cp -R data/DRIVER2/MISSIONS/UA data/DRIVER2/MISSIONS/UA_BACKUP"
