# -*- coding: utf-8 -*-
"""
Complete translation for FR, GE, IT, SP languages.
Translates all English fallback strings (lines 108-179) to respective languages.
"""

# French translations for lines 108-179
FR_TRANSLATIONS = {
    # Lines 108-179 (missing in original FR_GAME.LTXT)
    "Gate Racing": "Course de Portes",
    "Trailblazer": "Pionnier",
    "Checkpoint": "Point de Contrôle",
    "Survival": "Survie",
    "Cops N Robbers": "Flics et Voleurs",
    "Language": "Langue",
    "Undercover": "Infiltré",
    "Take A Ride": "Balade Libre",
    "Driving Games": "Jeux de Conduite",
    "Multiplayer Menu": "Menu Multijoueur",
    "Options": "Options",
    "Replays": "Rediffusions",
    "Secret": "Secret",
    "Cheats": "Codes de Triche",
    "Credits": "Crédits",
    "Quit": "Quitter",
    "New Game": "Nouvelle Partie",
    "Load Game": "Charger Partie",
    "Replay Mission": "Rejouer Mission",
    "View Movies": "Voir Films",
    "Load Replay": "Charger Rediffusion",
    "Sound": "Son",
    "Controls": "Contrôles",
    "Gameplay": "Jouabilité",
    "Graphics": "Graphiques",
    "Music Volume": "Volume Musique",
    "SFX Volume": "Volume Effets",
    "Pad Setup": "Config Manette",
    "Vibration": "Vibration",
    "Camera": "Caméra",
    "Difficulty": "Difficulté",
    "Easy": "Facile",
    "Normal": "Normal",
    "Hard": "Difficile",
    "Resolution": "Résolution",
    "Fullscreen": "Plein Écran",
    "VSync": "Sync Verticale",
    "Antialiasing": "Anticrénelage",
    "Shadows": "Ombres",
    "Reflections": "Reflets",
    "Weather Effects": "Effets Météo",
    "Traffic Density": "Densité Trafic",
    "Dawn": "Aube",
    "Day": "Jour",
    "Dusk": "Crépuscule",
    "Night": "Nuit",
    "Clear": "Clair",
    "Rainy": "Pluvieux",
    "Wet": "Mouillé",
    "Yes": "Oui",
    "No": "Non",
    "On": "Activé",
    "Off": "Désactivé",
    "Back": "Retour",
    "Accept": "Accepter",
    "Cancel": "Annuler",
    "Delete": "Supprimer",
    "Overwrite": "Écraser",
    "Are you sure?": "Êtes-vous sûr?",
    "Loading...": "Chargement...",
    "Saving...": "Sauvegarde...",
    "Please Wait": "Veuillez Patienter",
    "Mission Failed": "Mission Échouée",
    "Mission Complete": "Mission Réussie",
    "Paused": "Pause",
    "Resume": "Reprendre",
    "Restart": "Recommencer",
    "Quit Mission": "Quitter Mission",
    "Main Menu": "Menu Principal",
    "Player 1": "Joueur 1",
    "Player 2": "Joueur 2",
}

# German translations
GE_TRANSLATIONS = {
    "Gate Racing": "Tor-Rennen",
    "Trailblazer": "Wegbereiter",
    "Checkpoint": "Kontrollpunkt",
    "Survival": "Überleben",
    "Cops N Robbers": "Räuber und Gendarm",
    "Language": "Sprache",
    "Undercover": "Verdeckt",
    "Take A Ride": "Freie Fahrt",
    "Driving Games": "Fahrspiele",
    "Multiplayer Menu": "Mehrspieler-Menü",
    "Options": "Optionen",
    "Replays": "Wiederholungen",
    "Secret": "Geheim",
    "Cheats": "Cheats",
    "Credits": "Abspann",
    "Quit": "Beenden",
    "New Game": "Neues Spiel",
    "Load Game": "Spiel Laden",
    "Replay Mission": "Mission Wiederholen",
    "View Movies": "Filme Ansehen",
    "Load Replay": "Wiederholung Laden",
    "Sound": "Ton",
    "Controls": "Steuerung",
    "Gameplay": "Spielweise",
    "Graphics": "Grafik",
    "Music Volume": "Musiklautstärke",
    "SFX Volume": "Effektlautstärke",
    "Pad Setup": "Controller-Setup",
    "Vibration": "Vibration",
    "Camera": "Kamera",
    "Difficulty": "Schwierigkeit",
    "Easy": "Leicht",
    "Normal": "Normal",
    "Hard": "Schwer",
    "Resolution": "Auflösung",
    "Fullscreen": "Vollbild",
    "VSync": "VSync",
    "Antialiasing": "Kantenglättung",
    "Shadows": "Schatten",
    "Reflections": "Reflexionen",
    "Weather Effects": "Wettereffekte",
    "Traffic Density": "Verkehrsdichte",
    "Dawn": "Morgendämmerung",
    "Day": "Tag",
    "Dusk": "Abenddämmerung",
    "Night": "Nacht",
    "Clear": "Klar",
    "Rainy": "Regnerisch",
    "Wet": "Nass",
    "Yes": "Ja",
    "No": "Nein",
    "On": "An",
    "Off": "Aus",
    "Back": "Zurück",
    "Accept": "Akzeptieren",
    "Cancel": "Abbrechen",
    "Delete": "Löschen",
    "Overwrite": "Überschreiben",
    "Are you sure?": "Sind Sie sicher?",
    "Loading...": "Laden...",
    "Saving...": "Speichern...",
    "Please Wait": "Bitte Warten",
    "Mission Failed": "Mission Gescheitert",
    "Mission Complete": "Mission Erfolgreich",
    "Paused": "Pausiert",
    "Resume": "Fortsetzen",
    "Restart": "Neustart",
    "Quit Mission": "Mission Beenden",
    "Main Menu": "Hauptmenü",
    "Player 1": "Spieler 1",
    "Player 2": "Spieler 2",
}

# Italian translations
IT_TRANSLATIONS = {
    "Gate Racing": "Corsa a Porte",
    "Trailblazer": "Apripista",
    "Checkpoint": "Punto di Controllo",
    "Survival": "Sopravvivenza",
    "Cops N Robbers": "Guardie e Ladri",
    "Language": "Lingua",
    "Undercover": "Sotto Copertura",
    "Take A Ride": "Giro Libero",
    "Driving Games": "Giochi di Guida",
    "Multiplayer Menu": "Menu Multigiocatore",
    "Options": "Opzioni",
    "Replays": "Replay",
    "Secret": "Segreto",
    "Cheats": "Trucchi",
    "Credits": "Crediti",
    "Quit": "Esci",
    "New Game": "Nuova Partita",
    "Load Game": "Carica Partita",
    "Replay Mission": "Ripeti Missione",
    "View Movies": "Guarda Filmati",
    "Load Replay": "Carica Replay",
    "Sound": "Audio",
    "Controls": "Controlli",
    "Gameplay": "Giocabilità",
    "Graphics": "Grafica",
    "Music Volume": "Volume Musica",
    "SFX Volume": "Volume Effetti",
    "Pad Setup": "Configurazione Pad",
    "Vibration": "Vibrazione",
    "Camera": "Telecamera",
    "Difficulty": "Difficoltà",
    "Easy": "Facile",
    "Normal": "Normale",
    "Hard": "Difficile",
    "Resolution": "Risoluzione",
    "Fullscreen": "Schermo Intero",
    "VSync": "VSync",
    "Antialiasing": "Antialiasing",
    "Shadows": "Ombre",
    "Reflections": "Riflessi",
    "Weather Effects": "Effetti Meteo",
    "Traffic Density": "Densità Traffico",
    "Dawn": "Alba",
    "Day": "Giorno",
    "Dusk": "Tramonto",
    "Night": "Notte",
    "Clear": "Sereno",
    "Rainy": "Piovoso",
    "Wet": "Bagnato",
    "Yes": "Sì",
    "No": "No",
    "On": "Attivo",
    "Off": "Disattivo",
    "Back": "Indietro",
    "Accept": "Accetta",
    "Cancel": "Annulla",
    "Delete": "Elimina",
    "Overwrite": "Sovrascrivi",
    "Are you sure?": "Sei sicuro?",
    "Loading...": "Caricamento...",
    "Saving...": "Salvataggio...",
    "Please Wait": "Attendere Prego",
    "Mission Failed": "Missione Fallita",
    "Mission Complete": "Missione Completata",
    "Paused": "In Pausa",
    "Resume": "Riprendi",
    "Restart": "Ricomincia",
    "Quit Mission": "Esci Missione",
    "Main Menu": "Menu Principale",
    "Player 1": "Giocatore 1",
    "Player 2": "Giocatore 2",
}

# Spanish translations
SP_TRANSLATIONS = {
    "Gate Racing": "Carrera de Puertas",
    "Trailblazer": "Pionero",
    "Checkpoint": "Punto de Control",
    "Survival": "Supervivencia",
    "Cops N Robbers": "Policías y Ladrones",
    "Language": "Idioma",
    "Undercover": "Encubierto",
    "Take A Ride": "Paseo Libre",
    "Driving Games": "Juegos de Conducción",
    "Multiplayer Menu": "Menú Multijugador",
    "Options": "Opciones",
    "Replays": "Repeticiones",
    "Secret": "Secreto",
    "Cheats": "Trucos",
    "Credits": "Créditos",
    "Quit": "Salir",
    "New Game": "Nueva Partida",
    "Load Game": "Cargar Partida",
    "Replay Mission": "Repetir Misión",
    "View Movies": "Ver Películas",
    "Load Replay": "Cargar Repetición",
    "Sound": "Sonido",
    "Controls": "Controles",
    "Gameplay": "Jugabilidad",
    "Graphics": "Gráficos",
    "Music Volume": "Volumen Música",
    "SFX Volume": "Volumen Efectos",
    "Pad Setup": "Configuración Mando",
    "Vibration": "Vibración",
    "Camera": "Cámara",
    "Difficulty": "Dificultad",
    "Easy": "Fácil",
    "Normal": "Normal",
    "Hard": "Difícil",
    "Resolution": "Resolución",
    "Fullscreen": "Pantalla Completa",
    "VSync": "Sincronización Vertical",
    "Antialiasing": "Suavizado",
    "Shadows": "Sombras",
    "Reflections": "Reflejos",
    "Weather Effects": "Efectos Climáticos",
    "Traffic Density": "Densidad Tráfico",
    "Dawn": "Amanecer",
    "Day": "Día",
    "Dusk": "Atardecer",
    "Night": "Noche",
    "Clear": "Despejado",
    "Rainy": "Lluvioso",
    "Wet": "Mojado",
    "Yes": "Sí",
    "No": "No",
    "On": "Activado",
    "Off": "Desactivado",
    "Back": "Atrás",
    "Accept": "Aceptar",
    "Cancel": "Cancelar",
    "Delete": "Eliminar",
    "Overwrite": "Sobrescribir",
    "Are you sure?": "¿Estás seguro?",
    "Loading...": "Cargando...",
    "Saving...": "Guardando...",
    "Please Wait": "Por Favor Espere",
    "Mission Failed": "Misión Fallida",
    "Mission Complete": "Misión Completada",
    "Paused": "Pausado",
    "Resume": "Reanudar",
    "Restart": "Reiniciar",
    "Quit Mission": "Salir de Misión",
    "Main Menu": "Menú Principal",
    "Player 1": "Jugador 1",
    "Player 2": "Jugador 2",
}

def translate_file(lang_code, translations, input_file, output_file):
    """Translate missing lines in language file."""
    with open(input_file, 'r', encoding='utf-8') as f:
        en_lines = [line.strip() for line in f.readlines()]
    
    # Use latin1 for Western European languages, cp1251 for Cyrillic
    encoding = 'latin1' if lang_code in ['FR', 'GE', 'IT', 'SP'] else 'cp1251'
    
    with open(output_file, 'r', encoding=encoding) as f:
        current_lines = [line.strip() for line in f.readlines()]
    
    # Ensure we have 179 lines
    if len(current_lines) < 179:
        current_lines.extend([''] * (179 - len(current_lines)))
    
    # Translate lines 108-179 (indices 107-178)
    translated_count = 0
    for i in range(107, 179):
        en_text = en_lines[i] if i < len(en_lines) else ''
        if en_text in translations:
            current_lines[i] = translations[en_text]
            translated_count += 1
        elif not current_lines[i] or current_lines[i] == en_text:
            # If no translation available, keep English
            current_lines[i] = en_text
    
    # Write back
    with open(output_file, 'w', encoding=encoding) as f:
        for line in current_lines:
            f.write(line + '\r\n')
    
    print(f"{lang_code}: Translated {translated_count} new strings")

if __name__ == "__main__":
    EN_FILE = "custom_assets/DRIVER2/LANG/EN_GAME.LTXT"
    
    translate_file("FR", FR_TRANSLATIONS, EN_FILE, "custom_assets/DRIVER2/LANG/FR_GAME.LTXT")
    translate_file("GE", GE_TRANSLATIONS, EN_FILE, "custom_assets/DRIVER2/LANG/GE_GAME.LTXT")
    translate_file("IT", IT_TRANSLATIONS, EN_FILE, "custom_assets/DRIVER2/LANG/IT_GAME.LTXT")
    translate_file("SP", SP_TRANSLATIONS, EN_FILE, "custom_assets/DRIVER2/LANG/SP_GAME.LTXT")
    
    print("\n✅ All translations complete!")
